#!/usr/bin/env python

# By @Brunus_V
# version : alpha 1
# Licence :  WTFPL
# http://www.wtfpl.net/
# This script is an assembly and correction of several scripts from different sources that are not anymore up to date or just usuable

# You need : python-imaging python-nautilus python-pyexiv2
# Copy this script in your ~/.local/share/nautilus-python/extensions/

import os
import urllib
from gi.repository import Nautilus, GObject
import pyexiv2
import Image

class ColumnExtension(Nautilus.ColumnProvider, Nautilus.InfoProvider, GObject.GObject):
	def __init__(self):
		pass

	def get_columns(self):
		return (
			# exif support
			Nautilus.Column(
				name='NautilusPython::exif_pixeldimensions_column',
				attribute='exif_pixeldimensions',
				label='EXIF Image Size',
				description='EXIF Image size - pixel dimensions'),
			Nautilus.Column(
				name='NautilusPython::pixeldimensions_column',
				attribute='pixeldimensions',
				label='Image Size',
				description='Image size - pixel dimensions'),
		)

	def update_file_info(self, file):
		if file.get_uri_scheme() != 'file':
			return

		filename = urllib.unquote(file.get_uri()[7:])
		
		# jpeg EXIF handling (also try running it on other image types, if only for the image size)
		if file.is_mime_type('image/jpeg') or file.is_mime_type('image/png') or file.is_mime_type('image/gif') or file.is_mime_type('image/bmp'):
			try:
				img = pyexiv2.Image(filename)
				img.readMetadata()
				file.add_string_attribute('exif_pixeldimensions',str(img['Exif.Photo.PixelXDimension'])+'x'+str(img['Exif.Photo.PixelYDimension']))
			except:
				# no exif data?

				file.add_string_attribute('exif_pixeldimensions',"")
			# try read image info directly
			try:
				im = Image.open(filename)
				file.add_string_attribute('pixeldimensions',str(im.size[0])+'x'+str(im.size[1]))
			except:
				file.add_string_attribute('pixeldimensions',"[image read error]")
		else:
			file.add_string_attribute('exif_pixeldimensions', '')
			file.add_string_attribute('pixeldimensions', '')

		self.get_columns() 
	

	
